default_language_version:
  python: python3.8

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.5.0
    hooks:
      - id: check-added-large-files
        args: ["--maxkb=400"]
        exclude: "^()"
      - id: check-ast # Simply check whether the files parse as valid python.
      - id: check-json # This hook checks json files for parseable syntax.
      - id: pretty-format-json # This hook sets a standard for formatting JSON files.
      - id: check-yaml # Check that yaml-files can be parsed.
      - id: end-of-file-fixer # Ensures that a file is either empty, or ends with one newline.
      - id: requirements-txt-fixer # Sorts entries in requirements.txt
      - id: trailing-whitespace # This hook trims trailing whitespace.

  - repo: https://github.com/asottile/reorder_python_imports # Autosort python imports.
    rev: v2.3.0
    hooks:
      - id: reorder-python-imports

  - repo: https://github.com/psf/black # Black auto formatting.
    rev: stable
    hooks:
      - id: black
        exclude: "^(notebooks/)"

  - repo: https://gitlab.com/pycqa/flake8 # Flake8 formatting.
    rev: 3.7.7
    hooks:
      - id: flake8
        args: [--max-line-length=100]
        exclude: "^(notebooks/)"
